tencentyun/hadoop-cos

src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/ResettableFileInputStream.java
支持 PutObject 和 UploadPart 对File对象参数进行的重试；
=> feat: 支持File对象的异常重试

README.md
=> fix README.md hadoop-cos url

src/main/java/org/apache/hadoop/fs/Abortable.java, src/main/java/org/apache/hadoop/fs/CosFsDataOutputStream.java
add Abortable implements for CosFsDataOutputStream
=> add Abortable implements for CosFsDataOutputStream

src/main/java/org/apache/hadoop/fs/CosFsDataOutputStream.java
=> optimize abort process

src/main/java/org/apache/hadoop/fs/CosNFSDataOutputStream.java
flush wait for finish part uploads
=> flush wait for finish part uploads

src/main/java/org/apache/hadoop/fs/CosNFileReadTask.java
=> add retry for all IOException

pom.xml, src/main/java/org/apache/hadoop/fs/CosFileSystem.java, src/main/java/org/apache/hadoop/fs/CosHadoopFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNFSDataOutputStream.java, src/main/java/org/apache/hadoop/fs/CosNFSInputStream.java, src/main/java/org/apache/hadoop/fs/CosNFileReadTask.java, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/NativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/cosn/Constants.java
1) Add the shell to origin hadoop cos which use ofs network plugin to support the posix bucket
2) Fix the context loader of upload and read task to avoid stack.
3) From this version unite the inner and outer.
=> Rebuild the hadoop cos to support the merge bucket.

pom.xml, src/main/java/org/apache/hadoop/fs/CosFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNFileSystem.java, src/main/java/org/apache/hadoop/fs/RangerCredentialsClient.java, src/main/java/org/apache/hadoop/fs/cosn/Constants.java
1) pass through cos ranger policy url and auth md5 to posix ofs java SDK
2) change the init order to avoid useless import of ofs java SDK
3) add the list max keys configurations
4) change the version to v8.1.6 and begin to release
=> pass through cos ranger policy url and auth md5

src/main/java/org/apache/hadoop/fs/CosFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/cosn/Constants.java
meta engine can direct use the ofs ranger
=> control ranger

pom.xml
upgrade the cos_api.version to 5.6.100.
=> build: upgrade the cos_api.version to 5.6.100.

pom.xml, src/main/java/org/apache/hadoop/fs/CosFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNFSDataOutputStream.java, src/main/java/org/apache/hadoop/fs/CosNFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNSymlinkMetadata.java, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/NativeFileSystemStore.java
support the symbolic semantics
=> Feature support symlink

pom.xml, src/main/java/org/apache/hadoop/fs/ConsistencyChecker.java, src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNFSDataOutputStream.java, src/main/java/org/apache/hadoop/fs/CosNPosixExtensionDataOutputStream.java, src/main/java/org/apache/hadoop/fs/CosNUtils.java, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/NativeFileSystemStore.java
Reverts tencentyun/hadoop-cos#89
=> Revert "support client side encryption"

src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java
=> improve: add auto version number.

src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java
=> fix l5 update bug

pom.xml, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/cosn/TencentCloudL5EndpointResolver.java, src/main/java/org/apache/hadoop/fs/cosn/TencentCloudL5EndpointResolverImpl.java
fix l5 update route report inside of java sdk
=> fix l5 update route report inside of java sdk

src/main/java/org/apache/hadoop/fs/CosFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/NativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/cosn/BufferPool.java, src/main/java/org/apache/hadoop/fs/cosn/buffer/CosNMappedBufferFactory.java
support multiple cache dir and add option to disable create interface head operations
=> support multiple cache dir and add option to disable create interface head operations

src/main/java/org/apache/hadoop/fs/CosNFileSystem.java
=> fix: listStatus support directoryFirstEnabled switch.

src/main/java/org/apache/hadoop/fs/CosNFSBufferedFSInputStream.java, src/main/java/org/apache/hadoop/fs/CosNFileSystem.java
Support ByteBufferReadable interface in CosNFileSystem
=> Support ByteBufferReadable interface in CosNFileSystem

src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNCopyFileContext.java, src/main/java/org/apache/hadoop/fs/CosNDeleteFileContext.java, src/main/java/org/apache/hadoop/fs/CosNDeleteFileTask.java, src/main/java/org/apache/hadoop/fs/CosNFileSystem.java
改善 copy 和 delete 的线程池模型，优化 rename 性能。
=> perf: improve the rename performance.

pom.xml, src/main/java/org/apache/hadoop/fs/CosNFileSystem.java, src/test/java/org/apache/hadoop/fs/cosn/MemoryAllocatorTest.java
- Fix the metadata retrieval order error in getFileLinkStatus;
- Fix the package location for the MemoryAllocatorTest class.
=> fix: fix the getFileLinkStatus method.

pom.xml, src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/cosn/EndpointResolveHelper.java, src/main/java/org/apache/hadoop/fs/cosn/RetryableEndpointResolver.java, src/main/java/org/apache/hadoop/fs/cosn/TencentCloudL5EndpointResolver.java, src/main/java/org/apache/hadoop/fs/cosn/TencentCloudL5EndpointResolverImpl.java, src/main/java/org/apache/hadoop/fs/cosn/TencentPolarisEndpointResolver.java
=> feat: support the Tencent Polaris endpoint resolver.

pom.xml, src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/cosn/TencentPolarisSidecarClient.java, src/main/java/org/apache/hadoop/fs/cosn/TencentPolarisSidecarEndpointResolverImpl.java
elasticsearch因为安全原因不能直接使用北极星，需要使用sidecar 方式
=> add support for tencent polaris by sidecar

pom.xml, src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNUtils.java, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/cosn/BufferPool.java, src/test/java/org/apache/hadoop/fs/CosNFileSystemTestBase.java, src/test/java/org/apache/hadoop/fs/CosNFileSystemTestWithTimeout.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemAppend.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemCreate.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemDelete.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemGetFileStatus.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemListStatus.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemMkDirs.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemRename.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemSetAndGetXAttr.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemSymlink.java, src/test/java/org/apache/hadoop/fs/ITestCosNFileSystemTruncate.java, src/test/resources/core-site.xml
1.HTTP连接池关闭异常捕获，更友好的提示用户
2.tmp目录初始化校验读写权限
3.单元测试
4.支持ci/cd流水线提交代码自动执行单元测试
=> feature: add unit test and convering client-side issues

src/main/java/org/apache/hadoop/fs/CosNConfigKeys.java, src/main/java/org/apache/hadoop/fs/CosNFSInputStream.java, src/main/java/org/apache/hadoop/fs/CosNFileReadTask.java, src/main/java/org/apache/hadoop/fs/CosNFileStatus.java, src/main/java/org/apache/hadoop/fs/CosNFileSystem.java, src/main/java/org/apache/hadoop/fs/CosNativeFileSystemStore.java, src/main/java/org/apache/hadoop/fs/FileMetadata.java, src/main/java/org/apache/hadoop/fs/NativeFileSystemStore.java, src/test/java/org/apache/hadoop/fs/CosNFileSystemTestWithTimeout.java
=> feature:support COS AZ Consistency.
